version: '3'
services:
  jenkins-master:
    image: jenkins:lts
    container_name: jenkins-jcasc
    restart: always
    hostname: jenkins-master
    privileged: true
    user: root
    build:
      context: jenkins
      dockerfile: Dockerfile
    ports:
      - 50000:50000
      - 8080:8080
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
    volumes:
      - ./casc_configs:/var/jenkins_conf
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
