version: '3'
services:
  jenkins-master:
    image: jenkins:lts
    container_name: jenkins-jcasc
    restart: always
    hostname: jenkins-master
    privileged: true
    user: root
    env_file:
      - jenkins/build.properties
    build:
      context: jenkins
      dockerfile: Dockerfile
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#    secrets:
#      - github
#      - adminpw
#      - agent_private_key
#secrets:
#  github:
#    file: /var/deploy/secrets/github
#  adminpw:
#    file: /var/deploy/secrets/local
#  agent_private_key: #This should point to the private key you want your jenkins master to use when connecting to slaves.  So in AWS for example this would be your .pem file
#    file: ~/.ssh/id_rsa
