version: '3'
services:
  jenkins-master:
    image: jenkins:lts
    container_name: jenkins-master
    restart: always
    hostname: jenkins-master
    privileged: true
    user: root
    build:
      context: jenkins
      dockerfile: Dockerfile
    environment:
      JENKINS_AGENT_PORT: 5001
    ports:
      - 8080:8080
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
